### ISSUE TITLE
Remove images from core library

### ISSUE THREAD

**Issue by Jameskmonger** [buttercup-pw/buttercup-core#48]
From what I can tell, this library (buttercup-core) is intended to be the backbone of the [Buttercup](https://github.com/buttercup-pw/buttercup) application. Therefore, I'm not entirely sure if the images in the [/resources/](https://github.com/buttercup-pw/buttercup-core/tree/master/resources) folder actually belong in this library. The folder is almost 70kb in total, which would be quite a considerable amount to take off the size of the library.

**Comment by perry-mitchell** [comment]
You're right. This could be moved to an external project. The resources (images) will be for visual assets in the GUIs (desktop/mobile/web).
