### ISSUE TITLE
Add coverage around 963377

### ISSUE THREAD

**Issue by Jameskmonger** [buttercup-pw/buttercup-core#59]
I noticed that the fix for the occasionally failing tests (963377a08b0fd09d30829efd15a606cf3f147061) didn't have any tests added to check that the behaviour is now correct. It'd probably be good to get a test in there just for some robustness around the fix.

**Comment by perry-mitchell** [comment]
This can be addressed by fixing #56 (mgr) with a test for target group UUIDs beginning with 0.
