### ISSUE TITLE
How to set an ID for a group ?

### ISSUE THREAD

**Issue by srivignes** [buttercup-pw/buttercup-core#75]
@perry-mitchell  @sallar  
Hi, I need to know the process of setting an ID for the group in an archive.

I tried using managedGroup.getID() , but didn't get any output for it, also tried using archive.getGroupByID() and entered the groupname as the parameter, but only got 'null' as the output.

So can you please help me with this ?

**Comment by perry-mitchell** [comment]
Hi @srivignes, the managed group does indeed [provide getID()](https://github.com/buttercup-pw/buttercup-core/blob/master/source/classes/ManagedGroup.js#L126), so it should work.

`archive.getGroupByID()` needs the actual group ID, not the name. You probably want `Archive.findGroupsByTitle()`, [here](https://github.com/buttercup-pw/buttercup-core/blob/master/source/classes/Archive.js#L117).
