### ISSUE TITLE
npm install ERR!

### ISSUE THREAD

**Issue by snhasani** [buttercup-pw/buttercup-core#80]
This error occurred on webpack-react branch. I don't have any idea the JSON file which logged, where or what is it? :)
```bash
npm ERR! registry error parsing json
npm ERR! Darwin 15.5.0
npm ERR! argv "/Users/naser/.nvm/versions/node/v6.4.0/bin/node" "/Users/naser/.nvm/versions/node/v6.4.0/bin/npm" "install"
npm ERR! node v6.4.0
npm ERR! npm  v3.10.3

npm ERR! Unexpected token < in JSON at position 0
npm ERR! <html><head><meta http-equiv="Content-Type" content="text/html; charset=windows-1256"><title>MN8-4
npm ERR! </title></head><body><iframe src="http://10.10.34.34?type=Invalid Keyword&policy=MainPolicy " style="width: 100%; height: 100%" scrolling="no" marginwidth="0" marginheight="0" frameborder="0" vspace="0" hspace="0"></iframe></body></html>
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/naser/workspace/lab/sandbox/electron/buttercup/npm-debug.log
```

**Comment by sallar** [comment]
This is a weird error! I’ll look into it. Thanks.

**Comment by Jameskmonger** [comment]
@snhasani Would you mind opening the following URL in a browser from the same machine that you got the error in?

`http://10.10.34.34?type=Invalid Keyword&policy=MainPolicy`

I'm inclined to think that maybe there is a proxy between your machine and NPM's servers. Let me know what that URL gives you.

**Comment by snhasani** [comment]
@Jameskmonger that URL in Iran is blocked by government. I guess this is a network issue in my country and company network :disappointed: 
I test it with my private network after work.

@sallar no problem.

**Comment by sallar** [comment]
Ah yeah I just saw this URL. I guess it's the blocking then.

**Comment by perry-mitchell** [comment]
Closing - this issue sounds like it was meant for [buttercup-pw/buttercup](https://github.com/buttercup-pw/buttercup), not the core module.
